kind: pipeline
type: docker
name: app-template

trigger:
  event:
    - push
#    - pull_request

steps:
  - name: 检查和测试
    image: golang:latest
    volumes:
      - name: tools-cache
        path: /tmp/tools-cache
    commands:
      - env
      #- go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
      - make lint
      - make test

  - name: 构建打包
    image: golang:latest
    commands:
      - env
      - make build
    when:
      status:
        - success
      branch:
        - main
        - develop

  - name: 构建镜像
    image: docker:latest
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      registry_host:
        from_secret: registry_host
      registry_username:
        from_secret: registry_username
      registry_password:
        from_secret: registry_password
    commands:
      - echo "waiting 10 seconds..." && sleep 10
      - docker info
      - docker login -u $$registry_username -p $$registry_password $$registry_host
      - export REGISTRY_HOST=$$registry_host
      - export REPO_BRANCH=$(echo ${DRONE_BRANCH} |tr -d '/')
      - export SHORT_COMMIT_ID=$(echo ${CI_COMMIT_SHA}|cut -c1-8)
      - echo "waiting 3 seconds..." && sleep 3
      - |
        docker build --tag $${REGISTRY_HOST}/repo/app-template:$${SHORT_COMMIT_ID} \
          --build-arg EXTRA_BUILD_ARGS=-mod=vendor \
          --build-arg COMMIT_ID=${CI_COMMIT_SHA} \
          --build-arg COMMIT_TAG=${CI_COMMIT_TAG} \
          --build-arg VCS_BRANCH=$${REPO_BRANCH} \
          --build-arg VERSION=$${SHORT_COMMIT_ID} .
      - |
        docker push $${REGISTRY_HOST}/repo/app-template:$${SHORT_COMMIT_ID}
      - |
        docker rmi -f $(docker image ls |grep $${SHORT_COMMIT_ID} |awk '{print $3}')
    when:
      status:
        - success
      branch:
        - main
        - develop

  - name: 钉钉通知
    image: guoxudongdocker/drone-dingtalk
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status: [ failure, success ]

volumes:
  - name: artifacts-cache
    host:
      path: /workspace/artifacts
  - name: tools-cache
    host:
      path: /workspace/tools-cache
  - name: dockersock
    host:
      path: /var/run/docker.sock
